version: '3.8'

services:
  frontend:
    build:
      context: ./apps/alpha
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - API_URL=http://backend:3000
    networks:
      - frontend_net
      - backend_net
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/beta
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=codeexec
      - NODE_ENV=production
      - LOG_LEVEL=info
    networks:
      - backend_net
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend_net

  postgres:
    image: postgres:15-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codeexec
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

networks:
  frontend_net:
  backend_net:

volumes:
  redis_data:
  postgres_data: 